name: calendarapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-232.0.dev <4.0.0'

dependencies:
  dynamic_app_icon:
    git:
      url: F:\work_sflutterstarter\dynamic_app_icon
      ref: 29c5058e606139e55da0a1431ed2507e55058b65
  flutter:
    sdk: flutter
  flutter_swipe_action_cell: ^3.1.0
  intl: ^0.18.0
  lunar: ^1.3.1
  shared_preferences: ^2.0.18
  synchronized: ^3.0.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
